[project]
name = "genai-study"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "agent",
    "models",
    "rag",
    "rich>=15.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.uv]
package = false

[tool.uv.sources]
agent = { workspace = true }
models = { workspace = true }
rag = { workspace = true }

[tool.uv.workspace]
members = [
    "rag",
    "models",
    "agent",
]

[tool.pytest.ini_options]
testpaths = ["rag/tests"]
