[project]
name = "rag"
version = "0.1.0"
description = "learn rag from scratch"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "hnswlib>=0.8.0",
    "llama-cpp-python>=0.3.35",
    "pymupdf>=1.28.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
